##########################        GRIN CONFIG        ##########################

#### Dataset params ###########################################################
#dataset_name: [bay_point, bay_bock]
dataset_name: bay_point
val_len: 0.1

window: 12  # 24에서 12로 감소
stride: 1

#### Training params ##########################################################
whiten_prob: 0.05
scale_target: True

epochs: 300
loss_fn: l1_loss
lr_scheduler: cosine
lr: 0.001
batch_size: 16  # 32에서 16으로 감소
batches_epoch: 80  # 160에서 80으로 감소

#### Model params #############################################################
model_name: 'grin'

hidden_size: 32  # 64에서 32로 감소
ff_size: 32  # 64에서 32로 감소
embedding_size: 4  # 8에서 4로 감소
n_layers: 1
kernel_size: 2
decoder_order: 1
layer_norm: false
ff_dropout: 0
merge_mode: 'mlp'
