#########################      INFERENCE CONFIG      ##########################

#### Experiment params ########################################################
root: 'log'
#dataset_name: [bay_point, bay_block]
#model_name: [spin, spin_h]
#exp_name: {exp_name}
dataset_name: bay_point
model_name: spin_h
exp_name: 20250518T220707_359413000

#### Data params ##############################################################
p_fault: 0
p_noise: 0.95  # [0.5, 0.75, 0.95]
test_mask_seed: [1043, 2043, 3043, 4043, 5043]

#### Windowing params #########################################################
batch_size: 32 # 128
